/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;


public class EsercizioPesistica extends Esercizio {
    private Int Ripetizioni;
    private Set<float> Zavorra = new HashSet<>();
    private TipoEsercizio Tipo;
    public Int getRipetizioni() {
        return Ripetizioni;
    }
    public Set<float> getZavorra() {
        return Zavorra;
    }
    public TipoEsercizio getTipo() {
        return Tipo;
    }
    public void setRipetizioni(Int Ripetizioni) {
        this.Ripetizioni = Ripetizioni;
    }
    public void setTipo(TipoEsercizio Tipo) {
        this.Tipo = Tipo;
    }
}