/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;


public class EsercizioCardio extends Esercizio {
    private void Durata;
    private void Difficoltà;
    public void getDurata() {
        return Durata;
    }
    public void getDifficoltà() {
        return Difficoltà;
    }
    public void setDurata(void Durata) {
        this.Durata = Durata;
    }
    public void setDifficoltà(void Difficoltà) {
        this.Difficoltà = Difficoltà;
    }
}