/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;


public abstract class Esercizio {
    private String Nome;
    private boolean Favorite;
    private Giornosettimana GiornoSettimana;
    private Set<Workout>  = new HashSet<>();
    public String getNome() {
        return Nome;
    }
    public boolean isFavorite() {
        return Favorite;
    }
    public Giornosettimana getGiornoSettimana() {
        return GiornoSettimana;
    }
    public Set<Workout> get() {
        return ;
    }
    public void setNome(String Nome) {
        this.Nome = Nome;
    }
    public void setFavorite(boolean Favorite) {
        this.Favorite = Favorite;
    }
    public void setGiornoSettimana(Giornosettimana GiornoSettimana) {
        this.GiornoSettimana = GiornoSettimana;
    }
    public void link(Workout _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }
    public void unlink(Workout _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };
    public void unlink(Workout _, Iterator<Workout> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }
    public void getEsercizio() {
    }
    public void setEsercizio() {
    }
}