/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;


public class Scheda {
    private Set<Workout>  = new HashSet<>();
    public Set<Workout> get() {
        return ;
    }
    public void link(Workout _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }
    public void unlink(Workout _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };
    public void unlink(Workout _, Iterator<Workout> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }
}