/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;


public class Workout {
    private Set<Scheda>  = new HashSet<>();
    private Set<Esercizio>  = new HashSet<>();
    public Set<Scheda> get() {
        return ;
    }
    public Set<Esercizio> get() {
        return ;
    }
    public void link(Scheda _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }
    public void link(Esercizio _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }
    public void unlink(Scheda _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };
    public void unlink(Scheda _, Iterator<Scheda> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }
    public void unlink(Esercizio _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };
    public void unlink(Esercizio _, Iterator<Esercizio> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }
}