/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGHetKqSG9QDFM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGHetKqSG9QDFM= >>
// ----------- >>
public enum Attrezzo {
    // ----------- << enum.literals >>
    // ----------- >>
    // ----------- << attribute.annotations@AAAAAAGHetOvBnLL+vE= >>
    // ----------- >>
    private final void Attribute1;

    public final void getAttribute1() {
        return Attribute1;
    }

// ----------- << enum.extras@AAAAAAGHetKqSG9QDFM= >>
// ----------- >>
}