/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGGu9L41U0AFKw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGu9L41U0AFKw= >>
// ----------- >>
public class EsercizioCardio extends Esercizio {
    // ----------- << attribute.annotations@AAAAAAGGu9OKpk9p3Xg= >>
    // ----------- >>
    private void Durata;

    // ----------- << attribute.annotations@AAAAAAGGu9PnlE/rqlU= >>
    // ----------- >>
    private void Difficoltà;

    public void getDurata() {
        return Durata;
    }

    public void getDifficoltà() {
        return Difficoltà;
    }

    public void setDurata(void Durata) {
        this.Durata = Durata;
    }

    public void setDifficoltà(void Difficoltà) {
        this.Difficoltà = Difficoltà;
    }

    // ----------- << method.annotations@AAAAAAGHetb2s39pyhU= >>
    // ----------- >>
    public void setDurata() {
    // ----------- << method.body@AAAAAAGHetb2s39pyhU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGHetcimoAwRZw= >>
    // ----------- >>
    public void setDifficoltà() {
    // ----------- << method.body@AAAAAAGHetcimoAwRZw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGGu9L41U0AFKw= >>
// ----------- >>
}