/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGGu8QOVEqR2lI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGu8QOVEqR2lI= >>
// ----------- >>
public abstract class Esercizio {
    // ----------- << attribute.annotations@AAAAAAGGu6m030nN0vU= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAGGu6v8NUnngPU= >>
    // ----------- >>
    private boolean Favorite;

    // ----------- << attribute.annotations@AAAAAAGHedvQ97tByT8= >>
    // ----------- >>
    private Giornosettimana GiornoSettimana;

    // ----------- << attribute.annotations@AAAAAAGHes6TLGb+qwM= >>
    // ----------- >>
    private TipoEsercizio TipoExe;

    // ----------- << attribute.annotations@AAAAAAGHes/8xGm57bw= >>
    // ----------- >>
    private int NripetizioniExe;

    // ----------- << attribute.annotations@AAAAAAGHetYx5n16o0o= >>
    // ----------- >>
    private Attrezzo Attrezzo;

    // ----------- << attribute.annotations@AAAAAAGHer8VNTuZiHg= >>
    // ----------- >>
    private Workout ;

    public String getNome() {
        return Nome;
    }

    public boolean isFavorite() {
        return Favorite;
    }

    public Giornosettimana getGiornoSettimana() {
        return GiornoSettimana;
    }

    public TipoEsercizio getTipoExe() {
        return TipoExe;
    }

    public int getNripetizioniExe() {
        return NripetizioniExe;
    }

    public Attrezzo getAttrezzo() {
        return Attrezzo;
    }

    public Workout get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setFavorite(boolean Favorite) {
        this.Favorite = Favorite;
    }

    public void setGiornoSettimana(Giornosettimana GiornoSettimana) {
        this.GiornoSettimana = GiornoSettimana;
    }

    public void setTipoExe(TipoEsercizio TipoExe) {
        this.TipoExe = TipoExe;
    }

    public void setNripetizioniExe(int NripetizioniExe) {
        this.NripetizioniExe = NripetizioniExe;
    }

    public void setAttrezzo(Attrezzo Attrezzo) {
        this.Attrezzo = Attrezzo;
    }

    public void set(Workout ) {
        this. = ;
    }

    public void link(Workout _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAGHedi507lLfdM= >>
    // ----------- >>
    public void getEsercizio() {
    // ----------- << method.body@AAAAAAGHedi507lLfdM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGHedlZIrmgZvE= >>
    // ----------- >>
    public void setEsercizio() {
    // ----------- << method.body@AAAAAAGHedlZIrmgZvE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGHes8fBmiLJAs= >>
    // ----------- >>
    public void AddExercise() {
    // ----------- << method.body@AAAAAAGHes8fBmiLJAs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGHes84u2jUi8Y= >>
    // ----------- >>
    public void DeleteExercise() {
    // ----------- << method.body@AAAAAAGHes84u2jUi8Y= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGGu8QOVEqR2lI= >>
// ----------- >>
}