/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGGu6jcY0mY9Lc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGu6jcY0mY9Lc= >>
// ----------- >>
public class EsercizioPesistica extends Esercizio {
    // ----------- << attribute.annotations@AAAAAAGGu6rzDEnXM74= >>
    // ----------- >>
    private Int Ripetizioni;

    // ----------- << attribute.annotations@AAAAAAGGu6u2hUnfxfM= >>
    // ----------- >>
    private Set<float> Zavorra = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGGu7nYaUnx/sk= >>
    // ----------- >>
    private TipoEsercizio Tipo;

    // ----------- << attribute.annotations@AAAAAAGHetU6H3wF8PM= >>
    // ----------- >>
    private void Attribute1;

    public Int getRipetizioni() {
        return Ripetizioni;
    }

    public Set<float> getZavorra() {
        return Zavorra;
    }

    public TipoEsercizio getTipo() {
        return Tipo;
    }

    public void getAttribute1() {
        return Attribute1;
    }

    public void setRipetizioni(Int Ripetizioni) {
        this.Ripetizioni = Ripetizioni;
    }

    public void setTipo(TipoEsercizio Tipo) {
        this.Tipo = Tipo;
    }

    public void setAttribute1(void Attribute1) {
        this.Attribute1 = Attribute1;
    }

    // ----------- << method.annotations@AAAAAAGHetaap33zS00= >>
    // ----------- >>
    public void AddWeight() {
    // ----------- << method.body@AAAAAAGHetaap33zS00= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGHetbHpX7wErc= >>
    // ----------- >>
    public void RemoveWeight() {
    // ----------- << method.body@AAAAAAGHetbHpX7wErc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGGu6jcY0mY9Lc= >>
// ----------- >>
}