/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGHedqwwLnXdis= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGHedqwwLnXdis= >>
// ----------- >>
public enum Giornosettimana {
    lunedi,
    martedi,
    mercoledi,
    giovedi,
    venerdi,
    sabato,
    domenica;

// ----------- << enum.extras@AAAAAAGHedqwwLnXdis= >>
// ----------- >>
}