/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGGu7pIiEn4Cew= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGu7pIiEn4Cew= >>
// ----------- >>
public enum TipoEsercizio {
    SuperSet,
    Stripping,
    Emom,
    DropSet;

// ----------- << enum.extras@AAAAAAGGu7pIiEn4Cew= >>
// ----------- >>
}