/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.oggetti.Model1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGGu8F3vEpg23I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGGu8F3vEpg23I= >>
// ----------- >>
public class Workout {
    // ----------- << attribute.annotations@AAAAAAGHesEBRUDMXqA= >>
    // ----------- >>
    private float Durata;

    // ----------- << attribute.annotations@AAAAAAGHesGSMkIFHkA= >>
    // ----------- >>
    private String GruppoMuscolare;

    // ----------- << attribute.annotations@AAAAAAGHes3MQGW3MNM= >>
    // ----------- >>
    private Giornosettimana GiornoSettimana;

    // ----------- << attribute.annotations@AAAAAAGHetBD9WpWdPk= >>
    // ----------- >>
    private int NSerieExe;

    // ----------- << attribute.annotations@AAAAAAGHesRi5Upe7KA= >>
    // ----------- >>
    private Scheda ;

    // ----------- << attribute.annotations@AAAAAAGGu9yzEldgvX4= >>
    // ----------- >>
    private Set<Scheda>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAGHer8VNTuY47k= >>
    // ----------- >>
    private Set<Esercizio>  = new HashSet<>();

    public float getDurata() {
        return Durata;
    }

    public String getGruppoMuscolare() {
        return GruppoMuscolare;
    }

    public Giornosettimana getGiornoSettimana() {
        return GiornoSettimana;
    }

    public int getNSerieExe() {
        return NSerieExe;
    }

    public Scheda get() {
        return ;
    }

    public Set<Scheda> get() {
        return ;
    }

    public Set<Esercizio> get() {
        return ;
    }

    public void setDurata(float Durata) {
        this.Durata = Durata;
    }

    public void setGruppoMuscolare(String GruppoMuscolare) {
        this.GruppoMuscolare = GruppoMuscolare;
    }

    public void setGiornoSettimana(Giornosettimana GiornoSettimana) {
        this.GiornoSettimana = GiornoSettimana;
    }

    public void setNSerieExe(int NSerieExe) {
        this.NSerieExe = NSerieExe;
    }

    public void set(Scheda ) {
        this. = ;
    }

    public void link(Scheda _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Scheda _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Esercizio _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink(Scheda _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Scheda _, Iterator<Scheda> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink(Esercizio _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Esercizio _, Iterator<Esercizio> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    // ----------- << method.annotations@AAAAAAGHesKGo0J+RR0= >>
    // ----------- >>
    public void Addexercise() {
    // ----------- << method.body@AAAAAAGHesKGo0J+RR0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGHesLtH0PU96U= >>
    // ----------- >>
    public void DeleteExercise() {
    // ----------- << method.body@AAAAAAGHesLtH0PU96U= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGGu8F3vEpg23I= >>
// ----------- >>
}